# Generated by Django 4.1.1 on 2022-09-22 00:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=512)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2022, 9, 22, 0, 48, 41, 944204, tzinfo=datetime.timezone.utc))),
                ('delete_date', models.DateTimeField(null=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 9, 22, 0, 48, 41, 944204, tzinfo=datetime.timezone.utc))),
                ('delete_date', models.DateTimeField(null=True)),
                ('modify_date', models.DateTimeField(null=True)),
                ('image_exist', models.SmallIntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('hit', models.IntegerField(default=0)),
                ('comments_num', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_main', models.SmallIntegerField(default=0)),
                ('boarads_category_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.boardcategories')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
