# Generated by Django 4.1.1 on 2022-09-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_comments_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boards',
            old_name='boarads_category_fk',
            new_name='boarads_category',
        ),
        migrations.RenameField(
            model_name='boards',
            old_name='boards_writer_fk',
            new_name='boards_writer',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comments_board_fk',
            new_name='comments_board',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comments_writer_fk',
            new_name='comments_writer',
        ),
    ]
