# Generated by Django 4.1.1 on 2022-09-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_rename_boarads_category_fk_boards_boarads_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boards',
            old_name='boarads_category',
            new_name='boards_category',
        ),
    ]
