# Generated by Django 4.1.1 on 2022-09-20 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_address_user_detail_address_user_postcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(default=datetime.date(2022, 9, 20)),
        ),
    ]
