# Generated by Django 4.1.1 on 2022-09-20 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default=datetime.datetime(2022, 9, 20, 3, 33, 27, 907518, tzinfo=datetime.timezone.utc)),
        ),
    ]
