# Generated by Django 4.1.1 on 2022-09-21 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_phone_number_alter_user_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default=datetime.datetime(2022, 9, 21, 4, 43, 29, 92485, tzinfo=datetime.timezone.utc)),
        ),
    ]
