# Generated by Django 4.1.1 on 2022-09-22 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default=datetime.datetime(2022, 9, 22, 0, 44, 24, 525363, tzinfo=datetime.timezone.utc)),
        ),
    ]
