# Generated by Django 4.1.1 on 2022-09-22 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default=datetime.datetime(2022, 9, 22, 0, 49, 25, 117259, tzinfo=datetime.timezone.utc)),
        ),
    ]
