# Generated by Django 4.1.1 on 2022-10-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='boards_written',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='comments_written',
            field=models.IntegerField(default=0),
        ),
    ]
