# Generated by Django 4.1.1 on 2022-11-10 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_boards_written_user_comments_written'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username_is_changed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
