# Generated by Django 4.1.1 on 2022-11-10 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_username_is_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username_is_changed',
        ),
    ]
