# Generated by Django 4.1.1 on 2022-11-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_user_username_is_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
