# Generated by Django 4.1.1 on 2022-12-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable', models.TextField(null=True)),
                ('grade', models.IntegerField()),
                ('room', models.IntegerField()),
            ],
        ),
    ]
