# Generated by Django 4.1.1 on 2022-12-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetable_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='user',
            new_name='timetable_user',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='room',
        ),
    ]
