# Generated by Django 4.1.1 on 2022-12-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_timetable_timetable_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='timetable',
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
